// Code generated by MockGen. DO NOT EDIT.
// Source: ./mvgoutils.go
//
// Generated by this command:
//
//	mockgen -source=./mvgoutils.go -destination=../../mocks/mock_utils.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOpenmvgoUtilsInterface is a mock of OpenmvgoUtilsInterface interface.
type MockOpenmvgoUtilsInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOpenmvgoUtilsInterfaceMockRecorder
	isgomock struct{}
}

// MockOpenmvgoUtilsInterfaceMockRecorder is the mock recorder for MockOpenmvgoUtilsInterface.
type MockOpenmvgoUtilsInterfaceMockRecorder struct {
	mock *MockOpenmvgoUtilsInterface
}

// NewMockOpenmvgoUtilsInterface creates a new mock instance.
func NewMockOpenmvgoUtilsInterface(ctrl *gomock.Controller) *MockOpenmvgoUtilsInterface {
	mock := &MockOpenmvgoUtilsInterface{ctrl: ctrl}
	mock.recorder = &MockOpenmvgoUtilsInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOpenmvgoUtilsInterface) EXPECT() *MockOpenmvgoUtilsInterfaceMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockOpenmvgoUtilsInterface) Check(e error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Check", e)
}

// Check indicates an expected call of Check.
func (mr *MockOpenmvgoUtilsInterfaceMockRecorder) Check(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockOpenmvgoUtilsInterface)(nil).Check), e)
}

// CopyFile mocks base method.
func (m *MockOpenmvgoUtilsInterface) CopyFile(src, dst string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyFile", src, dst)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopyFile indicates an expected call of CopyFile.
func (mr *MockOpenmvgoUtilsInterfaceMockRecorder) CopyFile(src, dst any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyFile", reflect.TypeOf((*MockOpenmvgoUtilsInterface)(nil).CopyFile), src, dst)
}

// DownloadFile mocks base method.
func (m *MockOpenmvgoUtilsInterface) DownloadFile(url string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadFile", url)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadFile indicates an expected call of DownloadFile.
func (mr *MockOpenmvgoUtilsInterfaceMockRecorder) DownloadFile(url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadFile", reflect.TypeOf((*MockOpenmvgoUtilsInterface)(nil).DownloadFile), url)
}

// EnsureDir mocks base method.
func (m *MockOpenmvgoUtilsInterface) EnsureDir(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureDir", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureDir indicates an expected call of EnsureDir.
func (mr *MockOpenmvgoUtilsInterfaceMockRecorder) EnsureDir(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureDir", reflect.TypeOf((*MockOpenmvgoUtilsInterface)(nil).EnsureDir), path)
}

// RunCommand mocks base method.
func (m *MockOpenmvgoUtilsInterface) RunCommand(name string, args []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunCommand", name, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunCommand indicates an expected call of RunCommand.
func (mr *MockOpenmvgoUtilsInterfaceMockRecorder) RunCommand(name, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunCommand", reflect.TypeOf((*MockOpenmvgoUtilsInterface)(nil).RunCommand), name, args)
}
