# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.3'

    - name: Install mockgen
      run: go install go.uber.org/mock/mockgen@latest
    
    - name: Install tparse
      run: go install github.com/mfridman/tparse@latest

    - name: Run go generate
      run: go generate ./...

    - name: Build
      run: go build -v cmd/cli/main.go

    - name: Test
      run: make test
